application: collabpaint
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: collabpaint.application

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
